### ISSUE TITLE
Problem Running Makeflow with Shakespeare on SGE

### ISSUE THREAD

**Issue by npotteig** [cooperative-computing-lab/makeflow-examples#22] opened 2018-05-29 16:45 UTC
When I run the line
makeflow -T sge -d all shakespeare.makeflow

I get an error when it runs into a problem with perl.sfx and the sge.wrapper with the error message repeated.

batch: qsub -cwd -j y -V -N 'perl.sfx'  sge.wrapper
Unable to read script file because of error: error opening file: No such file or directory

The makeflow will run if I use the Makeflow file instead of shakespeare.makeflow and example.makeflow will also run using sge so it is probably a problem with the shakespeare makeflow.

**Comment by btovar** [comment] 2018-05-29 18:58
Where did you get the shakespeare.makeflow from?

Ben

**Comment by npotteig** [comment] 2018-05-29 20:14
Ben,

I got shakespeare.makeflow from the github repository called
makeflow-examples from the cooperative computing lab.

Nicholas

**Comment by btovar** [comment] 2018-05-29 20:49
Of course, I forgot about that repo.

I was able to reproduce your error. Thanks for your report!

Ben

**Comment by trshaffer** [comment] 2018-05-30 13:53
I've at least partially tracked this down to a bug in our SGE submit code. It appears UGE here requires job name to be alphanumeric, so running a command starting with `./perl.sfx` fails. I'm not convinced that this is the ultimate issue, though, as UGE's error is the opposite of helpful and I'm seeing file corruption. I wouldn't assume that `qsub` is *that* badly behaved.

**Comment by trshaffer** [comment] 2018-05-30 17:03
Looks like `qsub` (at the CRC) *was* that badly behaved. This should be resolved by cooperative-computing-lab/cctools#1906

**Comment by dthain** [comment] 2018-06-12 20:07
Ok to close?

**Closed** 2018-06-28 18:05 UTC
